# Generated by Django 5.2.4 on 2025-07-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hn_id', models.IntegerField(unique=True)),
                ('title', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('descendants', models.IntegerField()),
                ('by', models.CharField(max_length=100)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('keywords', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
